name = "hello-world-hazmania"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "hello-world-hazmania_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "hello-world-hazmania.wasm"
command = "npm run build:release"
